#! /bin/bash
### BEGIN INIT INFO
# Provides:          evarobot
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts evarobot as daemon
# Description:       starts evarobot as daemon
### END INIT INFO

. /opt/ros/indigo/setup.sh
. /home/pi/ros_catkin_ws/devel/setup.bash
. /home/pi/catkin_ws/devel/setup.bash
. /lib/lsb/init-functions

export ROS_MASTER_URI=http://evarobot:11311

HOME=/root
rospack profile > /dev/null

############### EDIT ME ##################

#APP_PATH=""

# path to daemon
DAEMON=`which roslaunch`

# startup args (ignored)
DAEMON_OPTS=`rospack find evarobot_start`/launch/start.launch

# script name
NAME=evarobot

# app name
DESC='evarobot starts'

RUN_AS=root

PID_FILE="/var/run/$NAME.pid"

if [ -e /etc/slave ]; then
  ENABLED=0
else
  ENABLED=1
fi

############### END EDIT ME ##################

RETVAL=0

test "$ENABLED" = 1 || exit 0

test -x "$DAEMON" || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $NAME: "

        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS
	
	RETVAL=$?
        if [ "$RETVAL" = 0 ]; then
            echo "[OK]"
        else
            echo "[FAILED]"
        fi
        ;;
  stop)
        echo -n "Stopping $NAME: "
        start-stop-daemon --signal INT --retry 5 --stop --pidfile $PID_FILE
	RETVAL=$?
        if [ "$RETVAL" = 0 ]; then
            echo "[OK]"
        else
            echo "[FAILED]"
        fi
        ;;
  status)
        
        status_of_proc -p $PID_FILE $DAEMON "$NAME"
	RETVAL=$?
        ;;

  restart|force-reload)
        echo -n "Restarting $NAME: "
        start-stop-daemon --stop --signal INT --retry 5 --oknodo --pidfile $PID_FILE
        sleep 1
        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS
        if [ $? ]; then
            echo "[OK]"
        else
            echo "[FAILED]"
        fi

        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit $RETVAL
